### ISSUE TITLE
OTBR add-on running, Form is successful, but Join finds no available networks

### ISSUE THREAD

**Issue by JAAlperin** [home-assistant/addons-development#105]
OTBR add-on log reports otbr-agent successfully started. Thread network was formed. WPAN service is associated. RCP state is leader. No devices have been commissioned.

So, why does “join” find no available Thread network?

Also, why is RCP:TxPower = 0 dBm?

**Comment by agners** [comment]
> So, why does “join” find no available Thread network?

The built-in web interface is not really production ready.

> Also, why is RCP:TxPower = 0 dBm?

Not sure about that, probably a default value somewhere?

I am closing the issue here since the OpenThread add-on in this repository is considered deprecated.
