### ISSUE TITLE
Added repository to HAOS, but no Add-ons are available to install

### ISSUE THREAD

**Issue by acidkill** [home-assistant/addons-development#116]
I want to give a Openthread Border Router a try, but can't install it. No plugins are visible to install on Add-on Store under the name Home Assistant Developer Add-ons.

**Comment by frenck** [comment]
Did you turn on advanced mode in your user profile?

**Comment by agners** [comment]
I assume this worked. The OpenThread Border Router is now available in the main repository anyways.
