### ISSUE TITLE
unable to update to vers 2

### ISSUE THREAD

**Issue by pippo73** [home-assistant/addons-development#125]
Hello, I've a system with 1.1.3 version. Now I would like to upgrade to 2.0.0.
But If I try to install the process does not work :-(
![image](https://github.com/home-assistant/addons-development/assets/757121/00faa674-d17c-427e-aaf0-8f09be57bafc)

**Comment by lboue** [comment]
I assume the new beta version will be released today based on the dependency shown here: 
[openthread_border_router/config.yaml](https://github.com/home-assistant/addons/blob/19b141f594c5825eb2da566df47aa9a1101dba33/openthread_border_router/config.yaml)
```
---
version: 2.0.0
slug: openthread_border_router
name: OpenThread Border Router
description: OpenThread Border Router add-on
url: >-
  https://github.com/home-assistant/addons/tree/master/openthread_border_router
arch:
  - aarch64
  - amd64
homeassistant: 2023.6.0.dev20230531

```

**Comment by agners** [comment]
Note that this add-on has been moved to the main add-on respoistory.

As @lboue explains, the Core restriction is the issue in your case. See also https://github.com/home-assistant/addons/issues/3073#issuecomment-1570011338.
