### ISSUE TITLE
ERROR: Invalid requirement: '-'

### ISSUE THREAD

**Issue by boris327** [home-assistant/addons-development#58]
please help me

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[20:37:49] INFO: Remove old deps
[20:37:49] INFO: Install pypi modules into deps
[20:37:49] INFO: Installing python package '-'
ERROR: Invalid requirement: '-'
[20:37:50] ERROR: Can't install -!
[20:37:50] ERROR: 
[cmd] /run.sh exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.

**Comment by agners** [comment]
What are you trying to do?

Make sure to set the configuration options.

**Comment by agners** [comment]
Closing, as this is an incomplete issue report.
