### ISSUE TITLE
[OpenThread Border Router] Looping on reboot

### ISSUE THREAD

**Issue by Calimerorulez** [home-assistant/addons-development#67]
Hi,

Just programmed a nRF52840 dongle, and installed the OTBR addon. At first launch it runs fine, but after a reboot, the log of the addon keeps on being filled by the following message, and the addon does not start any further:

```
ip6tables: Chain already exists.
[16:19:24] INFO: Setup OTBR firewall...
ip6tables: Chain already exists.
[16:19:25] INFO: Setup OTBR firewall...
ip6tables: Chain already exists.
[16:19:26] INFO: Setup OTBR firewall...
ip6tables: Chain already exists.
[16:19:27] INFO: Setup OTBR firewall...
ip6tables: Chain already exists.
[16:19:28] INFO: Setup OTBR firewall...
ip6tables: Chain already exists.
[16:19:29] INFO: Setup OTBR firewall...
ip6tables: Chain already exists.
[16:19:30] INFO: Setup OTBR firewall...
ip6tables: Chain already exists.
[16:19:31] INFO: Setup OTBR firewall...
ip6tables: Chain already exists.
```

**Comment by El-mou33** [comment]
Same problem! I linked successfully a nanoleaf bulb but after rebooting the addon the problem appeared.

**Comment by El-mou33** [comment]
Problem solved after turning off the OTBR firewall!!!!!!!!!

**Comment by El-mou33** [comment]
Please, close this issue if it's solved!

**Comment by Calimerorulez** [comment]
Well, turning off the firewall isn't exactly a solution, but whatever.

**Comment by agners** [comment]
This is the proper fix for the Firewall shutdown: https://github.com/home-assistant/addons-development/pull/74
