### ISSUE TITLE
silabs-multiprotocol (RCP) - When adding ZHA integration - Error: Cannot open file /usr/local/etc/zigbeed.conf

### ISSUE THREAD

**Issue by luvienm** [home-assistant/addons-development#83]
Hello,

I've built and flashed the Silicon Labs RCP Multi-PAN firmware to a ITead SONOFF Zigbee 3.0 USB Dongle Plus Model “ZBDongle-E”. After installing the dev addon "Silicon Labs Multiprotocol" and attempting to add a ZHA integration, the integration installation fails to complete and this error is in the log of the addon: Cannot open file /usr/local/etc/zigbeed.conf

This is attempted on RPI4 with HAOS 9.2. I also note that disabling OpenThread in the configuration doesn't disable it at all and the web interface is still available.

Log file entries from after attempting to add ZHA integration:

**Listening on port 9999 for connection...

Accepting connection.

Accepted connection 7.

Socket connection has been closed, restarting...

Restarting
Cannot open file /usr/local/etc/zigbeed.conf
By using this software, you are agreeing to the Silicon Labs MSLA found at https://www.silabs.com/about-us/legal/master-software-license-agreement.
[17:53:47:433] Info : Endpoint socket #12: Client disconnected. 1 connections
[17:53:48:439] Info : Client is using library v2
[17:53:48:444] Info : Endpoint socket #12: Client connected. 2 connections
Listening on port 9999 for connection...

Accepting connection.**

**Comment by MattWestb** [comment]
I have the same problem then adding ZHA to one addon that is up and running the OTBR OK.
I think its one timing problem then ZHA is setting up / forming the network.
If connecting one NCP / EZSP with USB or serial port and configuring ZHA its OK.
Then editing` \config\.storage\core.config_entries` and the record for ZHA and changing the local comport to the `socker` and restarting HA and ZHA is starting OK. Some time it can helping restarting the addon if ZHA is not starting OK and then reloading the ZHA integration from the integration card.
